name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code (without submodules to avoid Windows fork issue)
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1

      - name: Set up Docker to use Minikube's environment
        shell: cmd
        run: |
          call minikube docker-env > docker-env.bat
          call docker-env.bat

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-app-name:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/your-app-name:latest

      - name: Deploy all K8s manifests
        run: |
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\frontend-deployment.yaml"
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\frontend-service.yaml"
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\backend-deployment.yaml"
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\backend-service.yaml"
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\mongo-deployment.yaml"
          kubectl apply -f "D:\Semester 06\Theory Courses\SCD\Project\blogging-platform-main\k8s\mongo-service.yaml"
