name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Disable Git submodule recursion
        run: git config --global submodule.recurse false

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Set up Docker to use Minikube's environment (Windows)
        shell: powershell
        run: |
          minikube docker-env | Invoke-Expression

      - name: Build Docker image for frontend
        run: docker build -t your-dockerhub-username/blog-frontend ./frontend

      - name: Build Docker image for backend
        run: docker build -t your-dockerhub-username/blog-backend ./backend

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push frontend image
        run: docker push your-dockerhub-username/blog-frontend

      - name: Push backend image
        run: docker push your-dockerhub-username/blog-backend

      - name: Deploy all Kubernetes YAMLs to Minikube
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml
